/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package diapovision;

import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.BorderFactory;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import layout.VerticalFlowLayout;

/**
 *
 * @author arthur
 */
public class JfStructure extends javax.swing.JFrame {
    
    /**
     * Creates new form JfStructure
     */
    public JfStructure() {
        initComponents();
        panelListe.setLayout(new VerticalFlowLayout());
        panelListe.setBorder(BorderFactory.createLoweredBevelBorder());
        jScrollPane.setViewportView(panelListe);
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btAjouter = new javax.swing.JButton();
        btSuprimer = new javax.swing.JButton();
        jScrollPane = new javax.swing.JScrollPane();
        panelListe = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btAjouter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diapovision/icon/boutonAdd.png"))); // NOI18N
        btAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAjouterActionPerformed(evt);
            }
        });

        btSuprimer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diapovision/icon/boutonSuprimer.png"))); // NOI18N
        btSuprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSuprimerActionPerformed(evt);
            }
        });

        jScrollPane.setViewportView(panelListe);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btAjouter)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 410, Short.MAX_VALUE)
                .addComponent(btSuprimer))
            .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btAjouter, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btSuprimer, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 391, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSuprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSuprimerActionPerformed
        JpViniette.deleteSelected(panelListe);
        jScrollPane.setViewportView(panelListe);
    }//GEN-LAST:event_btSuprimerActionPerformed

    private void btAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAjouterActionPerformed
        Image[] imgs;
        
        try {
             imgs = rechercheImage();
         } catch (IOException ex) {
             Logger.getLogger(JfStructure.class.getName()).log(Level.SEVERE, null, ex);
             return;
         }
        if(imgs == null) return;
        for(Image img : imgs){
            JpImage pImg = new JpImage(img);
            JpViniette vignette = new JpViniette(pImg);
            panelListe.add(vignette);
        }
        jScrollPane.setViewportView(panelListe);
    }//GEN-LAST:event_btAjouterActionPerformed

    
    public Image[] rechercheImage() throws IOException{
        JFileChooser recherche = new JFileChooser();
        recherche.addChoosableFileFilter(new FileNameExtensionFilter("Image files", ImageIO.getReaderFileSuffixes()));
        recherche.setAcceptAllFileFilterUsed(false);
        recherche.setMultiSelectionEnabled(true);
        int showOpenDialog = recherche.showOpenDialog(this);
        if(showOpenDialog==JFileChooser.CANCEL_OPTION||showOpenDialog==JFileChooser.ERROR_OPTION){
            return null;
        }
        final File[] selectedFiles = recherche.getSelectedFiles();        
        Image[] images = new Image[selectedFiles.length];
        int i = 0;
        for(File selectedFile: selectedFiles){
            Image image = ImageIO.read(selectedFile);
            images[i++] = image;
        }        
        return images;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JfStructure.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JfStructure.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JfStructure.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JfStructure.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JfStructure().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAjouter;
    private javax.swing.JButton btSuprimer;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JPanel panelListe;
    // End of variables declaration//GEN-END:variables
    
    
    private void FileFilter(File f) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
