/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package diapovision;

import java.awt.Component;
import java.awt.Dimension;
import java.awt.GraphicsDevice;
import java.awt.Image;
import java.awt.Window;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.BorderFactory;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.filechooser.FileNameExtensionFilter;
import layout.VerticalFlowLayout;

/**
 *
 * @author arthur
 */
public class JfStructure extends javax.swing.JFrame {
    
    /**
     * Creates new form JfStructure
     */
    public JfStructure() {
        initComponents();
        panelListe.setLayout(new VerticalFlowLayout());
        panelListe.setBorder(BorderFactory.createLoweredBevelBorder());
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btAjouter = new javax.swing.JButton();
        btSuprimer = new javax.swing.JButton();
        jScrollPane = new javax.swing.JScrollPane();
        panelListe = new javax.swing.JPanel();
        btPlay = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btAjouter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diapovision/icon/boutonAdd.png"))); // NOI18N
        btAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAjouterActionPerformed(evt);
            }
        });

        btSuprimer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diapovision/icon/boutonSuprimer.png"))); // NOI18N
        btSuprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSuprimerActionPerformed(evt);
            }
        });

        jScrollPane.setViewportView(panelListe);

        btPlay.setText("Lecture");
        btPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPlayActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btAjouter)
                .addGap(164, 164, 164)
                .addComponent(btPlay)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 187, Short.MAX_VALUE)
                .addComponent(btSuprimer))
            .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btAjouter, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btSuprimer, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(btPlay))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 391, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSuprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSuprimerActionPerformed
        JpViniette.deleteSelected(panelListe);
        panelListe.repaint();
        panelListe.doLayout();
        jScrollPane.doLayout();
//        this.repaint();
    }//GEN-LAST:event_btSuprimerActionPerformed

    private void btAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAjouterActionPerformed
        Image img=null;
        
       // System.out.println("new picture "+dv.liste.lastIndexOf(img)+"  "+dv.liste.size());
        try {
             img = rechercheImage();
         } catch (IOException ex) {
             Logger.getLogger(JfStructure.class.getName()).log(Level.SEVERE, null, ex);
         }
        JpImage pImg = new JpImage(img);
        JpViniette vignette = new JpViniette(pImg);
        panelListe.add(vignette);
        jScrollPane.setViewportView(panelListe);
    }//GEN-LAST:event_btAjouterActionPerformed

    private void btPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPlayActionPerformed
        if(panelListe.getComponentCount()>0){
            
            GraphicsDevice myDevice = null;
            FullScreen fs = new FullScreen();
           // Window myWindow = fs;
            JpViniette pViniette = (JpViniette) panelListe.getComponent(0);
            fs.add(pViniette.getPImg());
            fs.start();
        }
    }//GEN-LAST:event_btPlayActionPerformed

    
    public Image rechercheImage() throws IOException{
        JFileChooser recherche = new JFileChooser();
        recherche.showOpenDialog(this);
        recherche.addChoosableFileFilter(new FileNameExtensionFilter("Image files", ImageIO.getReaderFileSuffixes()));
        recherche.setAcceptAllFileFilterUsed(false);
        Image image = ImageIO.read(recherche.getSelectedFile());        
        return image;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JfStructure.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JfStructure.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JfStructure.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JfStructure.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JfStructure().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAjouter;
    private javax.swing.JButton btPlay;
    private javax.swing.JButton btSuprimer;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JPanel panelListe;
    // End of variables declaration//GEN-END:variables
    
    
    private void FileFilter(File f) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
